name: The Family Business
favicon: null
layout_spectrum: 0.6163199571892619
typography_spectrum: 0.27446623309515417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dadbe0'
    - '#263204'
    - '#44590c'
    - '#5c73a6'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
